/**
 * Bundled Token Data - AUTO-GENERATED
 *
 * Generated by: node scripts/generate-token-bundle.js
 * Do not edit this file manually.
 */

import type { TokenFileData } from './tokens-loader';

import tok_semantic_light from '../../tokens/semantic/light.json';
import tok_semantic_dark from '../../tokens/semantic/dark.json';
import tok_component_accordion from '../../tokens/component/accordion.json';
import tok_component_accordionbody from '../../tokens/component/accordionbody.json';
import tok_component_action from '../../tokens/component/action.json';
import tok_component_alert from '../../tokens/component/alert.json';
import tok_component_badge from '../../tokens/component/badge.json';
import tok_component_beta_list_item_content from '../../tokens/component/beta-list-item-content.json';
import tok_component_beta_list_item_media from '../../tokens/component/beta-list-item-media.json';
import tok_component_bottom_actions from '../../tokens/component/bottom-actions.json';
import tok_component_button_quantity from '../../tokens/component/button-quantity.json';
import tok_component_button from '../../tokens/component/button.json';
import tok_component_callout from '../../tokens/component/callout.json';
import tok_component_cardheading from '../../tokens/component/cardheading.json';
import tok_component_checkbox from '../../tokens/component/checkbox.json';
import tok_component_chevron_xs from '../../tokens/component/chevron-xs.json';
import tok_component_content_card_v2 from '../../tokens/component/content-card-v2.json';
import tok_component_content_card from '../../tokens/component/content-card.json';
import tok_component_field_label from '../../tokens/component/field-label.json';
import tok_component_icon_button from '../../tokens/component/icon-button.json';
import tok_component_image_container from '../../tokens/component/image-container.json';
import tok_component_image from '../../tokens/component/image.json';
import tok_component_indicator from '../../tokens/component/indicator.json';
import tok_component_input_adornment from '../../tokens/component/input-adornment.json';
import tok_component_input_child from '../../tokens/component/input-child.json';
import tok_component_input from '../../tokens/component/input.json';
import tok_component_list_item from '../../tokens/component/list-item.json';
import tok_component_menu_item from '../../tokens/component/menu-item.json';
import tok_component_mini_product_card from '../../tokens/component/mini-product-card.json';
import tok_component_notification from '../../tokens/component/notification.json';
import tok_component_pill from '../../tokens/component/pill.json';
import tok_component_pillmedia from '../../tokens/component/pillmedia.json';
import tok_component_plp_card from '../../tokens/component/plp-card.json';
import tok_component_popoverbeak from '../../tokens/component/popoverbeak.json';
import tok_component_pricing_action from '../../tokens/component/pricing-action.json';
import tok_component_progress_bar_track from '../../tokens/component/progress-bar-track.json';
import tok_component_progress_bar from '../../tokens/component/progress-bar.json';
import tok_component_quantity_button from '../../tokens/component/quantity-button.json';
import tok_component_quantity_picker from '../../tokens/component/quantity-picker.json';
import tok_component_radio_button from '../../tokens/component/radio-button.json';
import tok_component_rating_increment from '../../tokens/component/rating-increment.json';
import tok_component_rating_meter from '../../tokens/component/rating-meter.json';
import tok_component_rating_star_half from '../../tokens/component/rating-star-half.json';
import tok_component_switch from '../../tokens/component/switch.json';
import tok_component_tab_group from '../../tokens/component/tab-group.json';
import tok_component_tab from '../../tokens/component/tab.json';
import tok_component_text_input_field from '../../tokens/component/text-input-field.json';
import tok_component_tile from '../../tokens/component/tile.json';
import tok_component_tilecontent from '../../tokens/component/tilecontent.json';
import tok_component_tilemedia from '../../tokens/component/tilemedia.json';
import tok_component_tooltip from '../../tokens/component/tooltip.json';
import tok_core_border from '../../tokens/core/border.json';
import tok_core_elevation from '../../tokens/core/elevation.json';
import tok_core_font_family from '../../tokens/core/font-family.json';
import tok_core_font_size from '../../tokens/core/font-size.json';
import tok_core_font_weight from '../../tokens/core/font-weight.json';
import tok_core_letter_spacing from '../../tokens/core/letter-spacing.json';
import tok_core_line_height from '../../tokens/core/line-height.json';
import tok_core_neutrals from '../../tokens/core/neutrals.json';
import tok_core_position from '../../tokens/core/position.json';
import tok_core_spacing from '../../tokens/core/spacing.json';
import tok_core_colors from '../../tokens/core/colors.json';
import tok_core_interaction from '../../tokens/core/interaction.json';

export const BUNDLED_TOKEN_FILES: TokenFileData[] = [
  { path: 'semantic/light', content: tok_semantic_light as unknown as Record<string, unknown> },
  { path: 'semantic/dark', content: tok_semantic_dark as unknown as Record<string, unknown> },
  { path: 'component/accordion', content: tok_component_accordion as unknown as Record<string, unknown> },
  { path: 'component/accordionbody', content: tok_component_accordionbody as unknown as Record<string, unknown> },
  { path: 'component/action', content: tok_component_action as unknown as Record<string, unknown> },
  { path: 'component/alert', content: tok_component_alert as unknown as Record<string, unknown> },
  { path: 'component/badge', content: tok_component_badge as unknown as Record<string, unknown> },
  { path: 'component/beta-list-item-content', content: tok_component_beta_list_item_content as unknown as Record<string, unknown> },
  { path: 'component/beta-list-item-media', content: tok_component_beta_list_item_media as unknown as Record<string, unknown> },
  { path: 'component/bottom-actions', content: tok_component_bottom_actions as unknown as Record<string, unknown> },
  { path: 'component/button-quantity', content: tok_component_button_quantity as unknown as Record<string, unknown> },
  { path: 'component/button', content: tok_component_button as unknown as Record<string, unknown> },
  { path: 'component/callout', content: tok_component_callout as unknown as Record<string, unknown> },
  { path: 'component/cardheading', content: tok_component_cardheading as unknown as Record<string, unknown> },
  { path: 'component/checkbox', content: tok_component_checkbox as unknown as Record<string, unknown> },
  { path: 'component/chevron-xs', content: tok_component_chevron_xs as unknown as Record<string, unknown> },
  { path: 'component/content-card-v2', content: tok_component_content_card_v2 as unknown as Record<string, unknown> },
  { path: 'component/content-card', content: tok_component_content_card as unknown as Record<string, unknown> },
  { path: 'component/field-label', content: tok_component_field_label as unknown as Record<string, unknown> },
  { path: 'component/icon-button', content: tok_component_icon_button as unknown as Record<string, unknown> },
  { path: 'component/image-container', content: tok_component_image_container as unknown as Record<string, unknown> },
  { path: 'component/image', content: tok_component_image as unknown as Record<string, unknown> },
  { path: 'component/indicator', content: tok_component_indicator as unknown as Record<string, unknown> },
  { path: 'component/input-adornment', content: tok_component_input_adornment as unknown as Record<string, unknown> },
  { path: 'component/input-child', content: tok_component_input_child as unknown as Record<string, unknown> },
  { path: 'component/input', content: tok_component_input as unknown as Record<string, unknown> },
  { path: 'component/list-item', content: tok_component_list_item as unknown as Record<string, unknown> },
  { path: 'component/menu-item', content: tok_component_menu_item as unknown as Record<string, unknown> },
  { path: 'component/mini-product-card', content: tok_component_mini_product_card as unknown as Record<string, unknown> },
  { path: 'component/notification', content: tok_component_notification as unknown as Record<string, unknown> },
  { path: 'component/pill', content: tok_component_pill as unknown as Record<string, unknown> },
  { path: 'component/pillmedia', content: tok_component_pillmedia as unknown as Record<string, unknown> },
  { path: 'component/plp-card', content: tok_component_plp_card as unknown as Record<string, unknown> },
  { path: 'component/popoverbeak', content: tok_component_popoverbeak as unknown as Record<string, unknown> },
  { path: 'component/pricing-action', content: tok_component_pricing_action as unknown as Record<string, unknown> },
  { path: 'component/progress-bar-track', content: tok_component_progress_bar_track as unknown as Record<string, unknown> },
  { path: 'component/progress-bar', content: tok_component_progress_bar as unknown as Record<string, unknown> },
  { path: 'component/quantity-button', content: tok_component_quantity_button as unknown as Record<string, unknown> },
  { path: 'component/quantity-picker', content: tok_component_quantity_picker as unknown as Record<string, unknown> },
  { path: 'component/radio-button', content: tok_component_radio_button as unknown as Record<string, unknown> },
  { path: 'component/rating-increment', content: tok_component_rating_increment as unknown as Record<string, unknown> },
  { path: 'component/rating-meter', content: tok_component_rating_meter as unknown as Record<string, unknown> },
  { path: 'component/rating-star-half', content: tok_component_rating_star_half as unknown as Record<string, unknown> },
  { path: 'component/switch', content: tok_component_switch as unknown as Record<string, unknown> },
  { path: 'component/tab-group', content: tok_component_tab_group as unknown as Record<string, unknown> },
  { path: 'component/tab', content: tok_component_tab as unknown as Record<string, unknown> },
  { path: 'component/text-input-field', content: tok_component_text_input_field as unknown as Record<string, unknown> },
  { path: 'component/tile', content: tok_component_tile as unknown as Record<string, unknown> },
  { path: 'component/tilecontent', content: tok_component_tilecontent as unknown as Record<string, unknown> },
  { path: 'component/tilemedia', content: tok_component_tilemedia as unknown as Record<string, unknown> },
  { path: 'component/tooltip', content: tok_component_tooltip as unknown as Record<string, unknown> },
  { path: 'core/border', content: tok_core_border as unknown as Record<string, unknown> },
  { path: 'core/elevation', content: tok_core_elevation as unknown as Record<string, unknown> },
  { path: 'core/font-family', content: tok_core_font_family as unknown as Record<string, unknown> },
  { path: 'core/font-size', content: tok_core_font_size as unknown as Record<string, unknown> },
  { path: 'core/font-weight', content: tok_core_font_weight as unknown as Record<string, unknown> },
  { path: 'core/letter-spacing', content: tok_core_letter_spacing as unknown as Record<string, unknown> },
  { path: 'core/line-height', content: tok_core_line_height as unknown as Record<string, unknown> },
  { path: 'core/neutrals', content: tok_core_neutrals as unknown as Record<string, unknown> },
  { path: 'core/position', content: tok_core_position as unknown as Record<string, unknown> },
  { path: 'core/spacing', content: tok_core_spacing as unknown as Record<string, unknown> },
  { path: 'core/colors', content: tok_core_colors as unknown as Record<string, unknown> },
  { path: 'core/interaction', content: tok_core_interaction as unknown as Record<string, unknown> },
];
